export const MAX_CHAT_MESSAGE_CHARACTERS = 500;
export const MAX_CHAT_HISTORY_MESSAGES = 30;
export const MAX_CHAT_HISTORY_MESSAGE_CHARACTERS = 5_000;
export const CHAT_CONTEXT_WINDOW_MESSAGES = 8;
export const MAX_CHAT_TURNS_PER_SESSION = 15;